# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pnYzLUOTy-7EZifBUEHNKi2jEucdcpZ

Import Library
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Read  File csv"""

df = pd.read_csv('dataset.csv')

df.head()

X = df.iloc[:,1:3]
y = df.iloc[:,-1]
X.head()

"""Normalization Dataset"""

from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
scaler.fit(X)
X_scaled_array = scaler.transform(X)
X_scaled = pd.DataFrame(X_scaled_array, columns = X.columns)

X_scaled.head()

df["tagable"].value_counts()

"""Visualization Data"""

import seaborn as sns

sns.set(style="white", color_codes=True)
sns.FacetGrid(df, hue="tagable", size=5) \
   .map(plt.scatter, "word_count", "edu_count") \
   .add_legend()

sns.FacetGrid(df, hue="tagable", size=6) \
   .map(sns.kdeplot, "word_count") \
   .add_legend()

sns.FacetGrid(df, hue="tagable", size=6) \
   .map(sns.kdeplot, "edu_count") \
   .add_legend()

sns.pairplot(df.drop("id", axis=1), hue="tagable", size=3)

